### ISSUE TITLE
Pet: Summon bug

### ISSUE THREAD

**Issue by 3nei** [jasongdove/LegionCore-7.3.5#44]
Every time a Warlock summons their pet (likely applies to pets of other classes as well), a new pet is created with a new name, instead of loading the existing one from the database.

**Comment by jasongdove** [comment]
Starting to work on this here https://github.com/jasongdove/LegionCore-7.3.5/pull/47 - like many issues in this core, it seems to be caused by incorrect caching. I think I'll update to actually load from db.
