### ISSUE TITLE
Extraction Tools

### ISSUE THREAD

**Issue by d3athbl0w** [jasongdove/LegionCore-7.3.5#64]
Are the extraction tools working? And if so, where could I find a full client that works with said extraction tools because I have a client downloaded from: https://wowdl.net/client/World-of-Warcraft-7.3.5.26972 but don't work

![image](https://github.com/user-attachments/assets/e6532199-74b0-4d3d-a251-99b720a567d4)

**Comment by jasongdove** [comment]
I don't have tools that properly generate the data for this core. For now, use the pre-generated data files linked from the README.

My long-term plan is to update this core to use the data files from TC 7.3.5, but that will take more time.

**Comment by d3athbl0w** [comment]
> I don't have tools that properly generate the data for this core. For now, use the pre-generated data files linked from the README.
> 
> My long-term plan is to update this core to use the data files from TC 7.3.5, but that will take more time.

Sounds good to me, thanks for updating this legion repository

**Comment by jasongdove** [comment]
I haven't done a ton of testing, but I think this will be fixed with https://github.com/jasongdove/LegionCore-7.3.5/pull/66

After that PR, the tools included in the repo (and all build artifacts) can be used with client 26972 to generate all required data files.

**Comment by jasongdove** [comment]
FYI - pre-built windows binaries are available on every commit - just click on the `Actions` tab and each build will have a `LegionCoreMainWin64VS2022` artifact attached. When this run finishes, it will have the tools that you can use to generate all data for this core https://github.com/jasongdove/LegionCore-7.3.5/actions/runs/11459547514
