### ISSUE TITLE
Extractors/Phasing

### ISSUE THREAD

**Issue by slash-design** [jasongdove/LegionCore-7.3.5#71]
Mate,

Do I understand your plan correctly, that you want to rewrite the entire phasing system ?

**Comment by jasongdove** [comment]
"Want" is a strong word lol, but I think the phasing system should be updated at least to where TC 7.3.5 was. If someone more familiar with phasing wants to take it on, it would be much appreciated. Otherwise I may get to it eventually.

**Comment by slash-design** [comment]
You have my utmost respect. :-)
That sounds very interesting what you have in mind :-)
I would love to help you, but for me the WinBuild is broken since comment 43d696028be551a7b40d2e3f0e6f5c9ea45a57c5

So unfortunately I can't :-(

**Comment by jasongdove** [comment]
Please compare your dependencies with those from the auto windows builds https://github.com/jasongdove/LegionCore-7.3.5/blob/main/.github/workflows/build-win-x64.yml - this project requires newer versions of dependencies than some other LegionCore-7.3.5 projects.

Or paste the specific error so we can troubleshoot.

**Comment by slash-design** [comment]
Thanks mate.
It was just a faulty boost installation :-)
